<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE compilation 
[
 <!ELEMENT compilation (mp3*) >
 <!ELEMENT mp3 (titre, artiste)   >
 <!ATTLIST mp3 id (CDATA) #REQUIRED >
 <!ELEMENT titre (#PCDATA)   >
 <!ELEMENT artiste (#PCDATA)   >
] >
<compilation>
 <mp3 id="1">
 <titre>Foule sentimentale</titre>
 <artiste>Alain Souchon</artiste>
 </mp3>
 <mp3 id="2">
 <titre>Solaar pleure</titre>
 <artiste>MC Solaar</artiste>
 </mp3>
 <mp3 id="3">
 <titre>Le baiser</titre>
 <titre>Le baiser</titre>
 <artiste>Alain Souchon</artiste>
 </mp3>
 <mp3 id="4">
 <titre>Pourtant</titre>
 <artiste>Vanessa Paradis</artiste>
 </mp3>
 <mp3 id="5">
 <titre>Chambre avec vue</titre>
 <artiste>Henri Salvador</artiste>
 </mp3>
</compilation>
